CREATE TABLE `RECIPEMAIN` (
  `RECIPENAME` varchar(255) NOT NULL,
  `FILENAME` varchar(255) DEFAULT NULL,
  `FILEDATA` LONGBLOB NOT NULL,
  `COMMENT` varchar(255) DEFAULT NULL,
  `NUMBER` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`RECIPENAME`)
);

CREATE TABLE IF NOT EXISTS `MATERIAL` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `RECIPENAME` varchar(255) NOT NULL,
  `MATERIAL` varchar(255) NOT NULL,
  `QUANTITY` varchar(255) NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `fk_recipe_material` (`RECIPENAME`),
  CONSTRAINT `fk_recipe_material` FOREIGN KEY (`RECIPENAME`) REFERENCES `RECIPEMAIN` (`RECIPENAME`) ON DELETE CASCADE
);

CREATE TABLE `HOWTOMAKE` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `RECIPENAME` varchar(255) NOT NULL,
  `FILENAME2` varchar(255) NOT NULL,
  `FILEDATA2` LONGBLOB NOT NULL,
  `HOWTOMAKE` varchar(255) NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `fk_recipe_howtomake` (`RECIPENAME`),
  CONSTRAINT `fk_recipe_howtomake` FOREIGN KEY (`RECIPENAME`) REFERENCES `recipemain` (`RECIPENAME`) ON DELETE CASCADE
);